Add random_func_return_range and its test
Purdue-EBEC/generic-grader pull request #83
Opened 2024-09-14 01:20 UTC by advaitjawaji

2024-09-18 16:03 UTC, jhcole requested changes

2024-09-18 16:03 UTC, jhcole commented on tests/random/test_random_func_return_range.py
> +        "reference": "import random as r\ndef test_function():\n    return r.randint(1, 10)",
These reference modules don't actually do anything.  Let's just set them to `pass`.

2024-09-21 05:36 UTC, advaitjawaji commented on src/generic_grader/random/random_func_return_range.py
> +        @reference_test
I believe we need the student_user which comes from reference_test

2024-09-21 05:36 UTC, advaitjawaji commented on src/generic_grader/random/random_func_return_range.py
> +            # self.student_user = User(self, o.sub_module, o.obj_name, o.patches)
If we make this a reference_test we don't need to create a student_user, this would maintain consistency

2024-09-21 05:48 UTC, advaitjawaji commented on src/generic_grader/random/random_func_return_range.py
> +        @reference_test
Removed reference_test and imported only SubUser

2024-09-21 05:49 UTC, advaitjawaji commented on src/generic_grader/random/random_func_return_range.py
> +            # self.student_user = User(self, o.sub_module, o.obj_name, o.patches)
Fixed

2024-09-27 22:04 UTC, merged